### PR TITLE
CI: try new shared configurations

### PR DESCRIPTION
**Pull request by klauer**
Updated conda recipe as well

Let's see what happens 🤷‍♂️

### CODE REVIEW

**Comment by klauer** [comment]
Pretty darn painless (cheers @zrylettc @hhslepicka)
pip-based testing is segfaulting relating to pyqt/X settings, but otherwise all looks good to me.

**Comment by hhslepicka** [comment]
Did I miss a package or dependency at the general env-ui setup yaml file?

**Comment by klauer** [comment]
@hhslepicka don't think so. Not sure why conda/pip are behaving differently here, but it doesn't seem to be a cause for concern (for either pytmc or the ci-helpers)

**Comment by klauer** [comment]
... and travis stopped reporting status here :(

**Comment by klauer** [comment]
Migrated CI to travis-ci.com (from travis-ci.org)

**Comment by klauer** [comment]
Check out the view config tab, very cool: https://travis-ci.com/github/slaclab/pytmc/builds/169950425/config

**Pull request merged**
