### PR TITLE
FIX: pragmas on motionstage

### PR DESCRIPTION
**Pull request by klauer**
There are some finer points about this that need to be discussed at some point, but for now this PR just fixes the usage of a pytmc pragma on an FB_MotionStage in conjunction with the stcmd generation script:

Bug:
```
Traceback (most recent call last):
  ...
  File "/reg/g/pcds/epics/R7.0.2-2.0/ioc/ads-ioc/v0.0.2/iocBoot/templates/st.cmd.template", line 63, in top-level template code
    epicsEnvSet("MOTOR_PREFIX",    "{{motor|epics_prefix}}")
  File "/usr/local/lib/python3.7/site-packages/pytmc/bin/stcmd.py", line 137, in epics_prefix
    return get_name(obj, user_config)[0]
  File "/usr/local/lib/python3.7/site-packages/pytmc/bin/stcmd.py", line 118, in get_name
    config = pragmas.squash_configs(*configs)
  File "/usr/local/lib/python3.7/site-packages/pytmc/pragmas.py", line 190, in squash_configs
    squashed['pv'].append(config.pop('pv', None))
AttributeError: 'tuple' object has no attribute 'pop'
```

Looks like `pragmas` functions were tweaked and `stcmd` was not updated to follow that - another hole in the test suite.

Now an `FB_MotionStage` with a pragma of `pv: my:prefix:AXIS1` will correctly generate the following:
```
epicsEnvSet("MOTOR_PREFIX",    "my:prefix:")
epicsEnvSet("MOTOR_NAME",      "AXIS1")
```
and a filter of the form `{{motor|pragma('precision', 3) }}` will get the `precision:` field from the `FB_MotionStage` pragma as well.

### CODE REVIEW

**Comment by klauer** [comment]
@ZLLentz the proposed `DUT_*` refactor should be based on this code.

**Comment by ZLLentz** [comment]
@klauer I'll start the refactor with a branch off of this branch. Is this ready for review? I think it looks good.

**Comment by klauer** [comment]
Yes, it should be ready for review.

**Comment by klauer** [comment]
Sounds good, @n-wbrown - apologies for the lazy coding! Since @ZLLentz's PR relies on this one, I'd like to merge this and push the docstring commit to his PR (or a separate one altogether). That OK?

**Pull request merged**
