### PR TITLE
FIX: default io type should be io, as per the docs

### PR DESCRIPTION
**Pull request by ZLLentz**
https://slaclab.github.io/pytmc/pragma_usage.html#io

### CODE REVIEW

**Comment by teddyrendahl** [comment]
Power cycling to get changes from #105

**Comment by klauer** [comment]
... on second thought, let's discuss this...

**Comment by ZLLentz** [comment]
The alternate PR would be one that changes the docs appropriately.

**Comment by teddyrendahl** [comment]
I'd vote for having the default not be "writable". I think the consequences of accidentally exposing an internal field is greater than not having a field be writable. 

That being said I'm not completely against @ZLLentz suggestion of removing the ambiguity and raising an error (or at least a warning if no `io` is specified)

**Comment by ZLLentz** [comment]
I think this is an important enough choice that I'd want it to have no default. If there was a default, I don't really care which we choose, I just want the docs and the code to be consistent. I wrote the ppm lib stuff assuming the io default, got burned, and I only want to rewrite it once.

**Comment by klauer** [comment]
@n-wbrown interesting - a prototyping mode could be useful. Thoughts @ZLLentz @teddyrendahl?

**Comment by ZLLentz** [comment]
I don't think adding an io line significantly slows down your prototyping speed. I wouldn't oppose these sorts of modes but I don't expect to get much use out of them personally.

**Comment by n-wbrown** [comment]
Merging to bring code behavior and docs in line with one another. We can certainly revisit and change this at a later date if anyone develops strong feelings for the topic.

**Pull request merged**
